In [1]:
import pandas as pd
import a_momentum as a_m
import imp
imp.reload(a_m)

/var/folders/h1/6sllxx6j0zb6l_hvj_9ys3qh0000gn/T/ipykernel_1043/3810460158.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

In [2]:
df = pd.read_csv("../csv/GLD.csv")
df.head(1)

         Date   Open       High    Low      Close  Adj Close   Volume
0  2004-11-18  44.43  44.490002  44.07  44.380001  44.380001  5992000

In [3]:
mod_df = a_m.A_moment(df,"Adj Close")
#mod_df -> module안에 class에서 self
#df -> __init__ 함수에 있는 df라는 매개변수에 들어갈 인자 값
#'Adj Close' --> __init__ 함수에서 col 이라는 매개변수에 들어갈 인자 값

In [4]:
mod_df.df

            Date   Adj Close   STD-YM
0     2004-11-18   44.380001  2004-11
1     2004-11-19   44.779999  2004-11
2     2004-11-22   44.950001  2004-11
3     2004-11-23   44.750000  2004-11
4     2004-11-24   45.049999  2004-11
...          ...         ...      ...
3668  2019-06-18  127.120003  2019-06
3669  2019-06-19  127.889999  2019-06
3670  2019-06-20  131.110001  2019-06
3671  2019-06-21  131.979996  2019-06
3672  2019-06-24  133.501907  2019-06

[3673 rows x 3 columns]

In [5]:
mod_df.col

'Adj Close'

In [6]:
mod_df.month_list
#클래스 안에 있는 변수를 호출 하는 방법
#클래스를 생성한 변수명, 클래스 안에 있는 변수명

array(['2004-11', '2004-12', '2005-01', '2005-02', '2005-03', '2005-04',
       '2005-05', '2005-06', '2005-07', '2005-08', '2005-09', '2005-10',
       '2005-11', '2005-12', '2006-01', '2006-02', '2006-03', '2006-04',
       '2006-05', '2006-06', '2006-07', '2006-08', '2006-09', '2006-10',
       '2006-11', '2006-12', '2007-01', '2007-02', '2007-03', '2007-04',
       '2007-05', '2007-06', '2007-07', '2007-08', '2007-09', '2007-10',
       '2007-11', '2007-12', '2008-01', '2008-02', '2008-03', '2008-04',
       '2008-05', '2008-06', '2008-07', '2008-08', '2008-09', '2008-10',
       '2008-11', '2008-12', '2009-01', '2009-02', '2009-03', '2009-04',
       '2009-05', '2009-06', '2009-07', '2009-08', '2009-09', '2009-10',
       '2009-11', '2009-12', '2010-01', '2010-02', '2010-03', '2010-04',
       '2010-05', '2010-06', '2010-07', '2010-08', '2010-09', '2010-10',
       '2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10',
       '2018-11', '2018-12', '2019-01', '2019-02', '2019-03', '2019-04',
       '2019-05', '2019-06'], dtype=object)

In [7]:
mod_df.create_df()
# 클래스 안에 있는 함수를 호출

             Adj Close   STD-YM       BF_1M      BF_12M
Date
2004-11-30   45.119999  2004-11    0.000000    0.000000
2004-12-31   43.799999  2004-12   45.119999    0.000000
2005-01-31   42.220001  2005-01   43.799999    0.000000
2005-02-28   43.529999  2005-02   42.220001    0.000000
2005-03-31   42.820000  2005-03   43.529999    0.000000
...                ...      ...         ...         ...
2019-02-28  123.989998  2019-02  124.750000  125.000000
2019-03-29  122.010002  2019-03  123.989998  125.790001
2019-04-30  121.199997  2019-04  122.010002  124.589996
2019-05-31  123.330002  2019-05  121.199997  123.099998
2019-06-24  133.501907  2019-06  123.330002  118.650002

[176 rows x 4 columns]

In [8]:
mod_df.add_trade()

날짜 :  2004-11-30 모멘텀 인덱스 :  nan flag :  False signal :
날짜 :  2004-12-31 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-01-31 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-02-28 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-03-31 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-04-29 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-05-31 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-06-30 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-07-29 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-08-31 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-09-30 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-10-31 모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  2005-11-30 모멘텀 인덱스 :  0.02836886144434536 flag :  True signal :  buy
날짜 :  2005-12-30 모멘텀 인덱스 :  0.12100454614165623 flag :  True signal :  buy
날짜 :  2006-01-31 모멘텀 인덱스 :  0.22169589716494786 flag :  True signal :  buy
날짜 :  2006-02-28 모멘텀 인덱스 :  0.3025500184367109 flag :  True signal :  buy
날짜 :  2006-03-31 모멘텀 인덱스 :  0.3094348435310603 flag :  True signal :  buy
날짜 :  2006-04-28 모멘텀 인덱스 :  0.3402537642562291 flag :  True signal :  buy
날짜 :  2006-05-31 모멘텀 인덱스 :  0.5627849429635081 flag :  True signal :  buy
날짜 :  2006-06-30 모멘텀 인덱스 :  0.4785912633193199 flag :  True signal :  buy
날짜 :  2006-07-31 모멘텀 인덱스 :  0.42993928070994847 flag :  True signal :  buy
날짜 :  2006-08-31 모멘텀 인덱스 :  0.45529947210601507 flag :  True signal :  buy
날짜 :  2006-09-29 모멘텀 인덱스 :  0.3338329692969384 flag :  True signal :  buy
날짜 :  2006-10-31 모멘텀 인덱스 :  0.281681000789612 flag :  True signal :  buy
날짜 :  2006-11-30 모멘텀 인덱스 :  0.22688400109507123 flag :  True signal :  buy
날짜 :  2006-12-29 모멘텀 인덱스 :  0.24835200665560264 flag :  True signal :  buy
날짜 :  2007-01-31 모멘텀 인덱스 :  0.11481477751649427 flag :  True signal :  buy
날짜 :  2007-02-28 모멘텀 인덱스 :  0.15623331549848385 flag :  True signal :  buy
날짜 :  2007-03-30 모멘텀 인덱스 :  0.1442341701973897 flag :  True signal :  buy
날짜 :  2007-04-30 모멘텀 인덱스 :  0.009986204331615012 flag :  True signal :  buy
날짜 :  2007-05-31 모멘텀 인덱스 :  0.04452736830792303 flag :  True signal :  buy
날짜 :  2007-06-29 모멘텀 인덱스 :  0.07039034786869203 flag :  True signal :  buy
날짜 :  2007-07-31 모멘텀 인덱스 :  0.017574366687777232 flag :  True signal :  buy
날짜 :  2007-08-31 모멘텀 인덱스 :  0.05618879344696115 flag :  True signal :  buy
날짜 :  2007-09-28 모멘텀 인덱스 :  0.11854709738444424 flag :  True signal :  buy
날짜 :  2007-10-31 모멘텀 인덱스 :  0.22028551725479706 flag :  True signal :  buy
날짜 :  2007-11-30 모멘텀 인덱스 :  0.2209971147848595 flag :  True signal :  buy
날짜 :  2007-12-31 모멘텀 인덱스 :  0.2232241927420373 flag :  True signal :  buy
날짜 :  2008-01-31 모멘텀 인덱스 :  0.27194194749523537 flag :  True signal :  buy
날짜 :  2008-02-29 모멘텀 인덱스 :  0.3748495468629869 flag :  True signal :  buy
날짜 :  2008-03-31 모멘텀 인덱스 :  0.4630362477345984 flag :  True signal :  buy
날짜 :  2008-04-30 모멘텀 인덱스 :  0.3475929257768924 flag :  True signal :  buy
날짜 :  2008-05-30 모멘텀 인덱스 :  0.32209338843311874 flag :  True signal :  buy
날짜 :  2008-06-30 모멘텀 인덱스 :  0.36066595739844187 flag :  True signal :  buy
날짜 :  2008-07-31 모멘텀 인덱스 :  0.3892688951319516 flag :  True signal :  buy
날짜 :  2008-08-29 모멘텀 인덱스 :  0.3541792853658725 flag :  True signal :  buy
날짜 :  2008-09-30 모멘텀 인덱스 :  0.11154940520883128 flag :  True signal :  buy
날짜 :  2008-10-31 모멘텀 인덱스 :  0.08204015204629278 flag :  True signal :  buy
날짜 :  2008-11-28 모멘텀 인덱스 :  -0.07734097258147954 flag :  False signal :
날짜 :  2008-12-31 모멘텀 인덱스 :  -0.02607326007850186 flag :  False signal :
날짜 :  2009-01-30 모멘텀 인덱스 :  -0.053391738437817526 flag :  False signal :
날짜 :  2009-02-27 모멘텀 인덱스 :  -0.05063424828446672 flag :  False signal :
날짜 :  2009-03-31 모멘텀 인덱스 :  0.024554727372869012 flag :  True signal :  buy
날짜 :  2009-04-30 모멘텀 인덱스 :  0.04189263607864668 flag :  True signal :  buy
날짜 :  2009-05-29 모멘텀 인덱스 :  -0.0020583191100622678 flag :  False signal :
날짜 :  2009-06-30 모멘텀 인덱스 :  0.05251635552480627 flag :  True signal :  buy
날짜 :  2009-07-31 모멘텀 인덱스 :  0.012211345199570678 flag :  True signal :  buy
날짜 :  2009-08-31 모멘텀 인덱스 :  0.14245501336990607 flag :  True signal :  buy
날짜 :  2009-09-30 모멘텀 인덱스 :  0.09791938403667588 flag :  True signal :  buy
날짜 :  2009-10-30 모멘텀 인덱스 :  0.38561821618268666 flag :  True signal :  buy
날짜 :  2009-11-30 모멘텀 인덱스 :  0.27667789258318765 flag :  True signal :  buy
날짜 :  2009-12-31 모멘텀 인덱스 :  0.33656961407430463 flag :  True signal :  buy
날짜 :  2010-01-29 모멘텀 인덱스 :  0.17522725167511233 flag :  True signal :  buy
날짜 :  2010-02-26 모멘텀 인덱스 :  0.1439058882836841 flag :  True signal :  buy
날짜 :  2010-03-31 모멘텀 인덱스 :  0.2121178689866845 flag :  True signal :  buy
날짜 :  2010-04-30 모멘텀 인덱스 :  0.24842443846995876 flag :  True signal :  buy
날짜 :  2010-05-28 모멘텀 인덱스 :  0.19916844695951497 flag :  True signal :  buy
날짜 :  2010-06-30 모멘텀 인덱스 :  0.3037946589164289 flag :  True signal :  buy
날짜 :  2010-07-30 모멘텀 인덱스 :  0.30348154908369684 flag :  True signal :  buy
날짜 :  2010-08-31 모멘텀 인덱스 :  0.23650958808330635 flag :  True signal :  buy
날짜 :  2010-09-30 모멘텀 인덱스 :  0.23500257430455385 flag :  True signal :  buy
날짜 :  2010-10-29 모멘텀 인덱스 :  0.24753735733480298 flag :  True signal :  buy
날짜 :  2010-11-30 모멘텀 인덱스 :  0.14683497186816807 flag :  True signal :  buy
날짜 :  2010-12-31 모멘텀 인덱스 :  0.26195136076696235 flag :  True signal :  buy
날짜 :  2011-01-31 모멘텀 인덱스 :  0.3091732947260597 flag :  True signal :  buy
날짜 :  2011-02-28 모멘텀 인덱스 :  0.1867860275975508 flag :  True signal :  buy
날짜 :  2011-03-31 모멘텀 인덱스 :  0.2635154455304849 flag :  True signal :  buy
날짜 :  2011-04-29 모멘텀 인덱스 :  0.21237863893569164 flag :  True signal :  buy
날짜 :  2011-05-31 모멘텀 인덱스 :  0.28171264169867016 flag :  True signal :  buy
날짜 :  2011-06-30 모멘텀 인덱스 :  0.2297830292570675 flag :  True signal :  buy
날짜 :  2011-07-29 모멘텀 인덱스 :  0.2641787386644512 flag :  True signal :  buy
날짜 :  2011-08-31 모멘텀 인덱스 :  0.29660870254572913 flag :  True signal :  buy
날짜 :  2011-09-30 모멘텀 인덱스 :  0.38941439639076236 flag :  True signal :  buy
날짜 :  2011-10-31 모멘텀 인덱스 :  0.19182630040062976 flag :  True signal :  buy
날짜 :  2011-11-30 모멘텀 인덱스 :  0.2357111096693416 flag :  True signal :  buy
날짜 :  2011-12-30 모멘텀 인덱스 :  0.22642736284294007 flag :  True signal :  buy
날짜 :  2012-01-31 모멘텀 인덱스 :  0.17032425388173777 flag :  True signal :  buy
날짜 :  2012-02-29 모멘텀 인덱스 :  0.22991423129698596 flag :  True signal :  buy
날짜 :  2012-03-30 모멘텀 인덱스 :  0.1746746162256927 flag :  True signal :  buy
날짜 :  2012-04-30 모멘텀 인덱스 :  0.06398897630731049 flag :  True signal :  buy
날짜 :  2012-05-31 모멘텀 인덱스 :  0.08179635178960432 flag :  True signal :  buy
날짜 :  2012-06-29 모멘텀 인덱스 :  0.03849311643835618 flag :  True signal :  buy
날짜 :  2012-07-31 모멘텀 인덱스 :  -0.019584251292499744 flag :  False signal :
날짜 :  2012-08-31 모멘텀 인덱스 :  -0.11945755053197415 flag :  False signal :
날짜 :  2012-09-28 모멘텀 인덱스 :  0.0389725615459009 flag :  True signal :  buy
날짜 :  2012-10-31 모멘텀 인덱스 :  0.027190170364292277 flag :  True signal :  buy
날짜 :  2012-11-30 모멘텀 인덱스 :  -0.019396948821579163 flag :  False signal :
날짜 :  2012-12-31 모멘텀 인덱스 :  0.09250606972478237 flag :  True signal :  buy
날짜 :  2013-01-31 모멘텀 인덱스 :  -0.04305707923993951 flag :  False signal :
날짜 :  2013-02-28 모멘텀 인덱스 :  -0.01880818145752805 flag :  False signal :
날짜 :  2013-03-28 모멘텀 인덱스 :  -0.05625459709642844 flag :  False signal :
날짜 :  2013-04-30 모멘텀 인덱스 :  -0.04589824419637256 flag :  False signal :
날짜 :  2013-05-31 모멘텀 인덱스 :  -0.058369550797043535 flag :  False signal :
날짜 :  2013-06-28 모멘텀 인덱스 :  -0.1370578241245206 flag :  False signal :
날짜 :  2013-07-31 모멘텀 인덱스 :  -0.23886512113026004 flag :  False signal :
날짜 :  2013-08-30 모멘텀 인덱스 :  -0.2208013748581088 flag :  False signal :
날짜 :  2013-09-30 모멘텀 인덱스 :  -0.2168247380116629 flag :  False signal :
날짜 :  2013-10-31 모멘텀 인덱스 :  -0.23167301166848875 flag :  False signal :
날짜 :  2013-11-29 모멘텀 인덱스 :  -0.2307136664128817 flag :  False signal :
날짜 :  2013-12-31 모멘텀 인덱스 :  -0.25503028008813033 flag :  False signal :
날짜 :  2014-01-31 모멘텀 인덱스 :  -0.2796525734426658 flag :  False signal :
날짜 :  2014-02-28 모멘텀 인덱스 :  -0.21509806535947718 flag :  False signal :
날짜 :  2014-03-31 모멘텀 인덱스 :  -0.17371314031168283 flag :  False signal :
날짜 :  2014-04-30 모멘텀 인덱스 :  -0.13420188038938485 flag :  False signal :
날짜 :  2014-05-30 모멘텀 인덱스 :  -0.07243128095028795 flag :  False signal :
날짜 :  2014-06-30 모멘텀 인덱스 :  0.011082184442261944 flag :  True signal :  buy
날짜 :  2014-07-31 모멘텀 인덱스 :  0.0006251484887869196 flag :  True signal :  buy
날짜 :  2014-08-29 모멘텀 인덱스 :  -0.08341997041375604 flag :  False signal :
날짜 :  2014-09-30 모멘텀 인덱스 :  -0.03370254513900617 flag :  False signal :
날짜 :  2014-10-31 모멘텀 인덱스 :  -0.09026146219291475 flag :  False signal :
날짜 :  2014-11-28 모멘텀 인덱스 :  -0.06661137696631425 flag :  False signal :
날짜 :  2014-12-31 모멘텀 인덱스 :  -0.03453325780572014 flag :  False signal :
날짜 :  2015-01-30 모멘텀 인덱스 :  -0.054209294835849686 flag :  False signal :
날짜 :  2015-02-27 모멘텀 인덱스 :  -0.03267517553654975 flag :  False signal :
날짜 :  2015-03-31 모멘텀 인덱스 :  -0.06027017991853256 flag :  False signal :
날짜 :  2015-04-30 모멘텀 인덱스 :  -0.08501044046843953 flag :  False signal :
날짜 :  2015-05-29 모멘텀 인덱스 :  -0.05779290044008978 flag :  False signal :
날짜 :  2015-06-30 모멘텀 인덱스 :  -0.10887219433071982 flag :  False signal :
날짜 :  2015-07-31 모멘텀 인덱스 :  -0.0893102851876999 flag :  False signal :
날짜 :  2015-08-31 모멘텀 인덱스 :  -0.15283385150303685 flag :  False signal :
날짜 :  2015-09-30 모멘텀 인덱스 :  -0.06359176545556977 flag :  False signal :
날짜 :  2015-10-30 모멘텀 인덱스 :  -0.05148236103382353 flag :  False signal :
날짜 :  2015-11-30 모멘텀 인덱스 :  -0.025064650565831292 flag :  False signal :
날짜 :  2015-12-31 모멘텀 인덱스 :  -0.10265895223351018 flag :  False signal :
날짜 :  2016-01-29 모멘텀 인덱스 :  -0.17812878521171616 flag :  False signal :
날짜 :  2016-02-29 모멘텀 인덱스 :  -0.07928724761407557 flag :  False signal :
날짜 :  2016-03-31 모멘텀 인덱스 :  0.04381484097079569 flag :  True signal :  buy
날짜 :  2016-04-29 모멘텀 인덱스 :  0.03674978376002658 flag :  True signal :  buy
날짜 :  2016-05-31 모멘텀 인덱스 :  0.08369854660295428 flag :  True signal :  buy
날짜 :  2016-06-30 모멘텀 인덱스 :  0.03283790069846315 flag :  True signal :  buy
날짜 :  2016-07-29 모멘텀 인덱스 :  0.20527971981320858 flag :  True signal :  buy
날짜 :  2016-08-31 모멘텀 인덱스 :  0.18526002573056433 flag :  True signal :  buy
날짜 :  2016-09-30 모멘텀 인덱스 :  0.16769603062234673 flag :  True signal :  buy
날짜 :  2016-10-31 모멘텀 인덱스 :  0.14949675710438903 flag :  True signal :  buy
날짜 :  2016-11-30 모멘텀 인덱스 :  0.19642861452960392 flag :  True signal :  buy
날짜 :  2016-12-30 모멘텀 인덱스 :  0.10141928938911193 flag :  True signal :  buy
날짜 :  2017-01-31 모멘텀 인덱스 :  0.02487147334842854 flag :  True signal :  buy
날짜 :  2017-02-28 모멘텀 인덱스 :  -0.026045145195930042 flag :  False signal :
날짜 :  2017-03-31 모멘텀 인덱스 :  0.013515845065588561 flag :  True signal :  buy
날짜 :  2017-04-28 모멘텀 인덱스 :  -0.03987060994952518 flag :  False signal :
날짜 :  2017-05-31 모멘텀 인덱스 :  0.04058244943274958 flag :  True signal :  buy
날짜 :  2017-06-30 모멘텀 인덱스 :  -0.04625601291803583 flag :  False signal :
날짜 :  2017-07-31 모멘텀 인덱스 :  -0.0849744095200623 flag :  False signal :
날짜 :  2017-08-31 모멘텀 인덱스 :  -0.032296834687424614 flag :  False signal :
날짜 :  2017-09-29 모멘텀 인덱스 :  0.0014326727270985717 flag :  True signal :  buy
날짜 :  2017-10-31 모멘텀 인덱스 :  -0.002952271560566433 flag :  False signal :
날짜 :  2017-11-30 모멘텀 인덱스 :  0.0798210111856823 flag :  True signal :  buy
날짜 :  2017-12-29 모멘텀 인덱스 :  0.10482617366274827 flag :  True signal :  buy
날짜 :  2018-01-31 모멘텀 인덱스 :  0.0700995135413367 flag :  True signal :  buy
날짜 :  2018-02-28 모멘텀 인덱스 :  0.0706198002863423 flag :  True signal :  buy
날짜 :  2018-03-29 모멘텀 인덱스 :  0.05289756525524281 flag :  True signal :  buy
날짜 :  2018-04-30 모멘텀 인덱스 :  0.041566648378736026 flag :  True signal :  buy
날짜 :  2018-05-31 모멘텀 인덱스 :  0.03291322252744422 flag :  True signal :  buy
날짜 :  2018-06-29 모멘텀 인덱스 :  0.04304356150763167 flag :  True signal :  buy
날짜 :  2018-07-31 모멘텀 인덱스 :  -0.017391287784679132 flag :  False signal :
날짜 :  2018-08-31 모멘텀 인덱스 :  -0.0781274996026069 flag :  False signal :
날짜 :  2018-09-28 모멘텀 인덱스 :  -0.06637604760032811 flag :  False signal :
날짜 :  2018-10-31 모멘텀 인덱스 :  -0.06555064333389649 flag :  False signal :
날짜 :  2018-11-30 모멘텀 인덱스 :  -0.04913291575776901 flag :  False signal :
날짜 :  2018-12-31 모멘텀 인덱스 :  -0.06558836125210898 flag :  False signal :
날짜 :  2019-01-31 모멘텀 인덱스 :  -0.05013710849765596 flag :  False signal :
날짜 :  2019-02-28 모멘텀 인덱스 :  -0.0020000000000000018 flag :  False signal :
날짜 :  2019-03-29 모멘텀 인덱스 :  -0.014309587293826365 flag :  False signal :
날짜 :  2019-04-30 모멘텀 인덱스 :  -0.020707874490982436 flag :  False signal :
날짜 :  2019-05-31 모멘텀 인덱스 :  -0.01543461438561522 flag :  False signal :
날짜 :  2019-06-24 모멘텀 인덱스 :  0.03944374143373386 flag :  True signal :  buy

/Users/chulwonchae/UBION/220914/a_momentum/__init__.py:33: RuntimeWarning: invalid value encountered in double_scalars
  self.momentum_index = self.month_last_df.loc[i, "BF_1M"] / self.month_last_df.loc[i, "BF_12M"] - 1
/Users/chulwonchae/UBION/220914/a_momentum/__init__.py:33: RuntimeWarning: divide by zero encountered in double_scalars
  self.momentum_index = self.month_last_df.loc[i, "BF_1M"] / self.month_last_df.loc[i, "BF_12M"] - 1

trade
       3570
buy     103
dtype: int64

In [9]:
mod_df.returns()

진입일 :  2005-11-30 진입 가격 :  49.099998
청산일 :  2005-12-01 진입 가격 :  49.099998 청산 가격 :  50.169998 | return :  1.021792261580133
진입일 :  2005-12-30 진입 가격 :  51.580002
청산일 :  2006-01-03 진입 가격 :  51.580002 청산 가격 :  53.119999 | return :  1.029856474220377
진입일 :  2006-01-31 진입 가격 :  56.700001
청산일 :  2006-02-01 진입 가격 :  56.700001 청산 가격 :  56.700001 | return :  1.0
진입일 :  2006-02-28 진입 가격 :  56.07
청산일 :  2006-03-01 진입 가격 :  56.07 청산 가격 :  56.099998 | return :  1.000535009809167
진입일 :  2006-03-31 진입 가격 :  58.099998
청산일 :  2006-04-03 진입 가격 :  58.099998 청산 가격 :  58.470001 | return :  1.0063683823190495
진입일 :  2006-04-28 진입 가격 :  65.089996
청산일 :  2006-05-01 진입 가격 :  65.089996 청산 가격 :  65.160004 | return :  1.0010755569872827
진입일 :  2006-05-31 진입 가격 :  64.230003
청산일 :  2006-06-01 진입 가격 :  64.230003 청산 가격 :  62.560001 | return :  0.9739996586953297
진입일 :  2006-06-30 진입 가격 :  61.23
청산일 :  2006-07-03 진입 가격 :  61.23 청산 가격 :  62.18 | return :  1.0155152702923405
진입일 :  2006-07-31 진입 가격 :  63.16
청산일 :  2006-08-01 진입 가격 :  63.16 청산 가격 :  64.32 | return :  1.0183660544648512
진입일 :  2006-08-31 진입 가격 :  62.290001
청산일 :  2006-09-01 진입 가격 :  62.290001 청산 가격 :  62.139999 | return :  0.9975918767443912
진입일 :  2006-09-29 진입 가격 :  59.470001
청산일 :  2006-10-02 진입 가격 :  59.470001 청산 가격 :  59.150002 | return :  0.9946191526043525
진입일 :  2006-10-31 진입 가격 :  60.240002
청산일 :  2006-11-01 진입 가격 :  60.240002 청산 가격 :  61.360001 | return :  1.0185922802592204
진입일 :  2006-11-30 진입 가격 :  64.389999
청산일 :  2006-12-01 진입 가격 :  64.389999 청산 가격 :  64.120003 | return :  0.99580686435482
진입일 :  2006-12-29 진입 가격 :  63.209999
청산일 :  2007-01-03 진입 가격 :  63.209999 청산 가격 :  62.279999 | return :  0.9852871378782967
진입일 :  2007-01-31 진입 가격 :  64.830002
청산일 :  2007-02-01 진입 가격 :  64.830002 청산 가격 :  65.220001 | return :  1.006015717846191
진입일 :  2007-02-28 진입 가격 :  66.480003
청산일 :  2007-03-01 진입 가격 :  66.480003 청산 가격 :  65.82 | return :  0.9900721574877185
진입일 :  2007-03-30 진입 가격 :  65.739998
청산일 :  2007-04-02 진입 가격 :  65.739998 청산 가격 :  65.849998 | return :  1.0016732583411396
진입일 :  2007-04-30 진입 가격 :  67.089996
청산일 :  2007-05-01 진입 가격 :  67.089996 청산 가격 :  66.690002 | return :  0.9940379486682337
진입일 :  2007-05-31 진입 가격 :  65.540001
청산일 :  2007-06-01 진입 가격 :  65.540001 청산 가격 :  66.440002 | return :  1.0137320870654245
진입일 :  2007-06-29 진입 가격 :  64.269997
청산일 :  2007-07-02 진입 가격 :  64.269997 청산 가격 :  65.019997 | return :  1.011669519760519
진입일 :  2007-07-31 진입 가격 :  65.790001
청산일 :  2007-08-01 진입 가격 :  65.790001 청산 가격 :  65.93 | return :  1.002127967743913
진입일 :  2007-08-31 진입 가격 :  66.519997
청산일 :  2007-09-04 진입 가격 :  66.519997 청산 가격 :  67.440002 | return :  1.0138305027283752
진입일 :  2007-09-28 진입 가격 :  73.510002
청산일 :  2007-10-01 진입 가격 :  73.510002 청산 가격 :  73.900002 | return :  1.0053054004814201
진입일 :  2007-10-31 진입 가격 :  78.620003
청산일 :  2007-11-01 진입 가격 :  78.620003 청산 가격 :  77.93 | return :  0.9912235694012885
진입일 :  2007-11-30 진입 가격 :  77.32
청산일 :  2007-12-03 진입 가격 :  77.32 청산 가격 :  78.279999 | return :  1.0124159208484222
진입일 :  2007-12-31 진입 가격 :  82.459999
청산일 :  2008-01-02 진입 가격 :  82.459999 청산 가격 :  84.860001 | return :  1.0291050452231998
진입일 :  2008-01-31 진입 가격 :  91.400002
청산일 :  2008-02-01 진입 가격 :  91.400002 청산 가격 :  89.349998 | return :  0.9775710727008518
진입일 :  2008-02-29 진입 가격 :  96.18
청산일 :  2008-03-03 진입 가격 :  96.18 청산 가격 :  97.239998 | return :  1.0110209814930338
진입일 :  2008-03-31 진입 가격 :  90.410004
청산일 :  2008-04-01 진입 가격 :  90.410004 청산 가격 :  86.860001 | return :  0.9607344005869085
진입일 :  2008-04-30 진입 가격 :  86.650002
청산일 :  2008-05-01 진입 가격 :  86.650002 청산 가격 :  83.989998 | return :  0.9693017433513735
진입일 :  2008-05-30 진입 가격 :  87.449997
청산일 :  2008-06-02 진입 가격 :  87.449997 청산 가격 :  87.959999 | return :  1.0058319270153893
진입일 :  2008-06-30 진입 가격 :  91.400002
청산일 :  2008-07-01 진입 가격 :  91.400002 청산 가격 :  92.660004 | return :  1.0137855795670552
진입일 :  2008-07-31 진입 가격 :  90.080002
청산일 :  2008-08-01 진입 가격 :  90.080002 청산 가격 :  89.57 | return :  0.9943383438201966
진입일 :  2008-08-29 진입 가격 :  81.709999
청산일 :  2008-09-02 진입 가격 :  81.709999 청산 가격 :  79.199997 | return :  0.9692815808258669
진입일 :  2008-09-30 진입 가격 :  85.07
청산일 :  2008-10-01 진입 가격 :  85.07 청산 가격 :  85.970001 | return :  1.0105795345009991
진입일 :  2008-10-31 진입 가격 :  71.339996
청산일 :  2008-11-03 진입 가격 :  71.339996 청산 가격 :  71.099998 | return :  0.9966358562733869
진입일 :  2009-03-31 진입 가격 :  90.279999
청산일 :  2009-04-01 진입 가격 :  90.279999 청산 가격 :  91.029999 | return :  1.0083074879077036
진입일 :  2009-04-30 진입 가격 :  87.269997
청산일 :  2009-05-01 진입 가격 :  87.269997 청산 가격 :  86.949997 | return :  0.9963332186203695
진입일 :  2009-06-30 진입 가격 :  91.18
청산일 :  2009-07-01 진입 가격 :  91.18 청산 가격 :  92.389999 | return :  1.0132704430796227
진입일 :  2009-07-31 진입 가격 :  93.349998
청산일 :  2009-08-03 진입 가격 :  93.349998 청산 가격 :  93.870003 | return :  1.0055704875323082
진입일 :  2009-08-31 진입 가격 :  93.400002
청산일 :  2009-09-01 진입 가격 :  93.400002 청산 가격 :  93.900002 | return :  1.0053533189431838
진입일 :  2009-09-30 진입 가격 :  98.849998
청산일 :  2009-10-01 진입 가격 :  98.849998 청산 가격 :  97.889999 | return :  0.9902883255495868
진입일 :  2009-10-30 진입 가격 :  102.529999
청산일 :  2009-11-02 진입 가격 :  102.529999 청산 가격 :  103.949997 | return :  1.0138495856222527
진입일 :  2009-11-30 진입 가격 :  115.639999
청산일 :  2009-12-01 진입 가격 :  115.639999 청산 가격 :  117.379997 | return :  1.0150466794798225
진입일 :  2009-12-31 진입 가격 :  107.309998
청산일 :  2010-01-04 진입 가격 :  107.309998 청산 가격 :  109.800003 | return :  1.0232038490952167
진입일 :  2010-01-29 진입 가격 :  105.959999
청산일 :  2010-02-01 진입 가격 :  105.959999 청산 가격 :  108.349998 | return :  1.0225556721645497
진입일 :  2010-02-26 진입 가격 :  109.43
청산일 :  2010-03-01 진입 가격 :  109.43 청산 가격 :  109.43 | return :  1.0
진입일 :  2010-03-31 진입 가격 :  108.949997
청산일 :  2010-04-01 진입 가격 :  108.949997 청산 가격 :  110.260002 | return :  1.0120239103815671
진입일 :  2010-04-30 진입 가격 :  115.360001
청산일 :  2010-05-03 진입 가격 :  115.360001 청산 가격 :  115.730003 | return :  1.0032073682107545
진입일 :  2010-05-28 진입 가격 :  118.879997
청산일 :  2010-06-01 진입 가격 :  118.879997 청산 가격 :  119.910004 | return :  1.0086642582940173
진입일 :  2010-06-30 진입 가격 :  121.68
청산일 :  2010-07-01 진입 가격 :  121.68 청산 가격 :  117.040001 | return :  0.9618672008547008
진입일 :  2010-07-30 진입 가격 :  115.489998
청산일 :  2010-08-02 진입 가격 :  115.489998 청산 가격 :  115.540001 | return :  1.0004329639004756
진입일 :  2010-08-31 진입 가격 :  122.080002
청산일 :  2010-09-01 진입 가격 :  122.080002 청산 가격 :  121.690002 | return :  0.9968053735778938
진입일 :  2010-09-30 진입 가격 :  127.910004
청산일 :  2010-10-01 진입 가격 :  127.910004 청산 가격 :  128.910004 | return :  1.0078179967846768
진입일 :  2010-10-29 진입 가격 :  132.619995
청산일 :  2010-11-01 진입 가격 :  132.619995 청산 가격 :  131.919998 | return :  0.9947217838456411
진입일 :  2010-11-30 진입 가격 :  135.419998
청산일 :  2010-12-01 진입 가격 :  135.419998 청산 가격 :  135.380005 | return :  0.9997046743421162
진입일 :  2010-12-31 진입 가격 :  138.720001
청산일 :  2011-01-03 진입 가격 :  138.720001 청산 가격 :  138.0 | return :  0.9948096814099648
진입일 :  2011-01-31 진입 가격 :  129.869995
청산일 :  2011-02-01 진입 가격 :  129.869995 청산 가격 :  130.800003 | return :  1.0071610690367703
진입일 :  2011-02-28 진입 가격 :  137.660004
청산일 :  2011-03-01 진입 가격 :  137.660004 청산 가격 :  140.029999 | return :  1.0172162932669973
진입일 :  2011-03-31 진입 가격 :  139.860001
청산일 :  2011-04-01 진입 가격 :  139.860001 청산 가격 :  139.199997 | return :  0.9952809667147077
진입일 :  2011-04-29 진입 가격 :  152.369995
청산일 :  2011-05-02 진입 가격 :  152.369995 청산 가격 :  150.410004 | return :  0.9871366340859957
진입일 :  2011-05-31 진입 가격 :  149.639999
청산일 :  2011-06-01 진입 가격 :  149.639999 청산 가격 :  149.910004 | return :  1.0018043638185268
진입일 :  2011-06-30 진입 가격 :  146.0
청산일 :  2011-07-01 진입 가격 :  146.0 청산 가격 :  144.929993 | return :  0.9926711849315069
진입일 :  2011-07-29 진입 가격 :  158.289993
청산일 :  2011-08-01 진입 가격 :  158.289993 청산 가격 :  157.720001 | return :  0.9963990648480222
진입일 :  2011-08-31 진입 가격 :  177.720001
청산일 :  2011-09-01 진입 가격 :  177.720001 청산 가격 :  177.869995 | return :  1.0008439905421787
진입일 :  2011-09-30 진입 가격 :  158.059998
청산일 :  2011-10-03 진입 가격 :  158.059998 청산 가격 :  160.960007 | return :  1.0183475201612997
진입일 :  2011-10-31 진입 가격 :  167.339996
청산일 :  2011-11-01 진입 가격 :  167.339996 청산 가격 :  167.380005 | return :  1.000239088089855
진입일 :  2011-11-30 진입 가격 :  170.130005
청산일 :  2011-12-01 진입 가격 :  170.130005 청산 가격 :  169.630005 | return :  0.9970610710321204
진입일 :  2011-12-30 진입 가격 :  151.990005
청산일 :  2012-01-03 진입 가격 :  151.990005 청산 가격 :  155.919998 | return :  1.0258569173676912
진입일 :  2012-01-31 진입 가격 :  169.309998
청산일 :  2012-02-01 진입 가격 :  169.309998 청산 가격 :  169.559998 | return :  1.0014765814361417
진입일 :  2012-02-29 진입 가격 :  164.289993
청산일 :  2012-03-01 진입 가격 :  164.289993 청산 가격 :  166.610001 | return :  1.0141214200429116
진입일 :  2012-03-30 진입 가격 :  162.119995
청산일 :  2012-04-02 진입 가격 :  162.119995 청산 가격 :  162.940002 | return :  1.0050580250758088
진입일 :  2012-04-30 진입 가격 :  161.880005
청산일 :  2012-05-01 진입 가격 :  161.880005 청산 가격 :  161.320007 | return :  0.9965406598548103
진입일 :  2012-05-31 진입 가격 :  151.619995
청산일 :  2012-06-01 진입 가격 :  151.619995 청산 가격 :  157.5 | return :  1.0387811976909775
진입일 :  2012-06-29 진입 가격 :  155.190002
청산일 :  2012-07-02 진입 가격 :  155.190002 청산 가격 :  155.089996 | return :  0.999355589930336
진입일 :  2012-09-28 진입 가격 :  171.889999
청산일 :  2012-10-01 진입 가격 :  171.889999 청산 가격 :  172.289993 | return :  1.0023270347450524
진입일 :  2012-10-31 진입 가격 :  166.830002
청산일 :  2012-11-01 진입 가격 :  166.830002 청산 가격 :  166.070007 | return :  0.995444494450105
진입일 :  2012-12-31 진입 가격 :  162.020004
청산일 :  2013-01-02 진입 가격 :  162.020004 청산 가격 :  163.169998 | return :  1.0070978519417886
진입일 :  2014-06-30 진입 가격 :  128.039993
청산일 :  2014-07-01 진입 가격 :  128.039993 청산 가격 :  127.699997 | return :  0.9973446109138727
진입일 :  2014-07-31 진입 가격 :  123.389999
청산일 :  2014-08-01 진입 가격 :  123.389999 청산 가격 :  124.379997 | return :  1.0080233244835346
진입일 :  2016-03-31 진입 가격 :  117.639999
청산일 :  2016-04-01 진입 가격 :  117.639999 청산 가격 :  116.93 | return :  0.9939646463274792
진입일 :  2016-04-29 진입 가격 :  123.650002
청산일 :  2016-05-02 진입 가격 :  123.650002 청산 가격 :  123.239998 | return :  0.9966841569480929
진입일 :  2016-05-31 진입 가격 :  116.059998
청산일 :  2016-06-01 진입 가격 :  116.059998 청산 가격 :  115.940002 | return :  0.9989660864891624
진입일 :  2016-06-30 진입 가격 :  126.470001
청산일 :  2016-07-01 진입 가격 :  126.470001 청산 가격 :  128.410004 | return :  1.0153396298304764
진입일 :  2016-07-29 진입 가격 :  128.979996
청산일 :  2016-08-01 진입 가격 :  128.979996 청산 가격 :  129.220001 | return :  1.001860792428618
진입일 :  2016-08-31 진입 가격 :  124.779999
청산일 :  2016-09-01 진입 가격 :  124.779999 청산 가격 :  125.290001 | return :  1.0040872095214555
진입일 :  2016-09-30 진입 가격 :  125.639999
청산일 :  2016-10-03 진입 가격 :  125.639999 청산 가격 :  125.32 | return :  0.9974530483719599
진입일 :  2016-10-31 진입 가격 :  121.940002
청산일 :  2016-11-01 진입 가격 :  121.940002 청산 가격 :  122.730003 | return :  1.0064786041253304
진입일 :  2016-11-30 진입 가격 :  111.75
청산일 :  2016-12-01 진입 가격 :  111.75 청산 가격 :  111.540001 | return :  0.9981208143176734
진입일 :  2016-12-30 진입 가격 :  109.610001
청산일 :  2017-01-03 진입 가격 :  109.610001 청산 가격 :  110.470001 | return :  1.0078459993810236
진입일 :  2017-01-31 진입 가격 :  115.550003
청산일 :  2017-02-01 진입 가격 :  115.550003 청산 가격 :  115.199997 | return :  0.9969709563746181
진입일 :  2017-03-31 진입 가격 :  118.720001
청산일 :  2017-04-03 진입 가격 :  118.720001 청산 가격 :  119.349998 | return :  1.005306578459345
진입일 :  2017-05-31 진입 가격 :  120.620003
청산일 :  2017-06-01 진입 가격 :  120.620003 청산 가격 :  120.720001 | return :  1.000829033307187
진입일 :  2017-09-29 진입 가격 :  121.580002
청산일 :  2017-10-02 진입 가격 :  121.580002 청산 가격 :  120.769997 | return :  0.9933376790041508
진입일 :  2017-11-30 진입 가격 :  121.099998
청산일 :  2017-12-01 진입 가격 :  121.099998 청산 가격 :  121.589996 | return :  1.0040462263261143
진입일 :  2017-12-29 진입 가격 :  123.650002
청산일 :  2018-01-02 진입 가격 :  123.650002 청산 가격 :  125.150002 | return :  1.0121310147653697
진입일 :  2018-01-31 진입 가격 :  127.650002
청산일 :  2018-02-01 진입 가격 :  127.650002 청산 가격 :  128.070007 | return :  1.0032902858865604
진입일 :  2018-02-28 진입 가격 :  125.0
청산일 :  2018-03-01 진입 가격 :  125.0 청산 가격 :  124.720001 | return :  0.997760008
진입일 :  2018-03-29 진입 가격 :  125.790001
청산일 :  2018-04-02 진입 가격 :  125.790001 청산 가격 :  127.260002 | return :  1.0116861514294764
진입일 :  2018-04-30 진입 가격 :  124.589996
청산일 :  2018-05-01 진입 가격 :  124.589996 청산 가격 :  123.709999 | return :  0.9929368566638368
진입일 :  2018-05-31 진입 가격 :  123.099998
청산일 :  2018-06-01 진입 가격 :  123.099998 청산 가격 :  122.489998 | return :  0.9950446790421557
진입일 :  2018-06-29 진입 가격 :  118.650002
청산일 :  2018-07-02 진입 가격 :  118.650002 청산 가격 :  117.459999 | return :  0.9899704763595368
진입일 :  2019-06-24 진입 가격 :  133.501907
누적수익율 :  1.2641

             Adj Close   STD-YM trade  return   acc_rtn
Date
2004-11-18   44.380001  2004-11           1.0  1.000000
2004-11-19   44.779999  2004-11           1.0  1.000000
2004-11-22   44.950001  2004-11           1.0  1.000000
2004-11-23   44.750000  2004-11           1.0  1.000000
2004-11-24   45.049999  2004-11           1.0  1.000000
...                ...      ...   ...     ...       ...
2019-06-18  127.120003  2019-06           1.0  1.264127
2019-06-19  127.889999  2019-06           1.0  1.264127
2019-06-20  131.110001  2019-06           1.0  1.264127
2019-06-21  131.979996  2019-06           1.0  1.264127
2019-06-24  133.501907  2019-06   buy     1.0  1.264127

[3673 rows x 5 columns]